// Writes docs/test-evidence/coverage-summary.md from coverage/coverage-summary.json (run `npm test` first).
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const s = JSON.parse(readFileSync('coverage/coverage-summary.json', 'utf8'));
const rows = {};
for (const [file, v] of Object.entries(s)) {
  if (file === 'total') continue;
  const m = file.replaceAll('\\', '/').match(/(packages|services)\/([^/]+)\//);
  if (!m) continue;
  const key = `${m[1]}/${m[2]}`;
  rows[key] ??= { lines: [0, 0], branches: [0, 0], functions: [0, 0], statements: [0, 0] };
  for (const k of Object.keys(rows[key])) {
    rows[key][k][0] += v[k].covered;
    rows[key][k][1] += v[k].total;
  }
}
const pct = ([c, t]) => (t ? `${((100 * c) / t).toFixed(1)}%` : '–');
const lines = [
  '# Unit test coverage',
  '',
  `Generated by \`npm test\` (Vitest + v8 coverage) and \`node scripts/coverage-summary.mjs\`, ${new Date().toISOString().slice(0, 10)}.`,
  'Unit tests only. Integration (Testcontainers), contract (Pact), BDD and e2e tests are counted in',
  '[README.md](README.md). The CI gate is **≥ 80% for `packages/domain`** (pure logic). Services are mostly',
  'I/O wiring and are covered by the integration tests instead, so their unit coverage is low by design.',
  '',
  '| Package | Lines | Branches | Functions | Statements |',
  '|---|---|---|---|---|',
  ...Object.entries(rows)
    .sort()
    .map(([k, r]) => `| ${k} | ${pct(r.lines)} (${r.lines[0]}/${r.lines[1]}) | ${pct(r.branches)} | ${pct(r.functions)} | ${pct(r.statements)} |`),
  `| **total** | **${s.total.lines.pct}%** | ${s.total.branches.pct}% | ${s.total.functions.pct}% | ${s.total.statements.pct}% |`,
  '',
];
mkdirSync('docs/test-evidence', { recursive: true });
writeFileSync('docs/test-evidence/coverage-summary.md', lines.join('\n'));
console.log(lines.slice(7).join('\n'));
